# Generated by Django 2.0.3 on 2018-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0004_auto_20180325_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_two',
            name='image_first',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article_two',
            name='image_second',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article_two',
            name='image_third',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
