# Generated by Django 2.0.3 on 2018-03-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0005_auto_20180325_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_Two',
        ),
    ]
