# Generated by Django 2.0.3 on 2018-03-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0009_article_fourth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_Fourth',
        ),
    ]
