# Generated by Django 2.0.3 on 2018-03-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0011_article_fourth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_fourth',
            name='image_fifth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='image_first',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='image_fourth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='image_second',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='text_fifth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='text_fourth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='text_second',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='text_third',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='title_fifth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='title_fourth',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='title_second',
        ),
        migrations.RemoveField(
            model_name='article_fourth',
            name='title_third',
        ),
    ]
