# Generated by Django 2.0.3 on 2018-03-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0012_auto_20180331_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_fourth',
            name='title',
        ),
    ]
