# Generated by Django 2.0.3 on 2018-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0016_auto_20180415_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_Three',
        ),
        migrations.DeleteModel(
            name='Article_Two',
        ),
    ]
