# Generated by Django 2.0.3 on 2021-05-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_website', '0023_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
